services:
  - type: web
    name: windsurf-app
    env: node
    buildCommand: |
      # Install backend dependencies
      npm install
      
      # Build frontend
      cd client
      npm install --legacy-peer-deps
      CI=false npm run build
      
      # Debug info
      echo "===== DEBUGGING INFO ====="
      echo "Current location:"
      pwd
      echo "Client directory contents:"
      ls -la
      echo "Build folder contents:"
      ls -la build || echo "Build folder not found!"
      
      # Ensure parent directories exist
      cd ..
      echo "Project root contents before copy:"
      ls -la
      
      # Remove existing build directory if it exists
      rm -rf client/build
      
      # Move build directory to correct location
      cd client
      mkdir -p build
      mv build/* .
      cd ..
      
      echo "Final client/build contents:"
      ls -la client/build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://mdurgaprasad2422:1IJpgp0ODukxy7aZ@cluster0.kh0fh.mongodb.net/innovators_marketplace?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: your_jwt_secret_key
      - key: CLOUDINARY_CLOUD_NAME
        value: dk6nfol6b
      - key: CLOUDINARY_API_KEY
        value: "512913691958756"
      - key: CLOUDINARY_API_SECRET
        value: OTV9_c49lbH6xDVKQZyFCGbkWmo
      - key: PORT
        value: "10000"
      - key: CI
        value: "false"
