services:
  - type: web
    name: windsurf-app
    env: node
    buildCommand: |
      # Install root dependencies
      npm install
      
      # Build frontend
      cd client
      export CI=false
      export GENERATE_SOURCEMAP=false
      npm install --legacy-peer-deps
      npm run build
      
      # Debug build directory
      echo "Build directory contents:"
      ls -la build || echo "Build directory not found!"
      
      # Ensure build directory exists in the correct location
      cd ..
      rm -rf client/build
      mkdir -p client/build
      mv client/build/* client/build/ || echo "No files to move"
      
      # Debug final location
      echo "Final build directory contents:"
      ls -la client/build || echo "Final build directory not found!"
    startCommand: |
      # Debug directory structure
      echo "Current working directory: $(pwd)"
      echo "Directory contents:"
      ls -la
      echo "Client directory contents:"
      ls -la client
      echo "Build directory contents:"
      ls -la client/build || echo "Build directory not found"
      
      # Start the server
      node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://mdurgaprasad2422:1IJpgp0ODukxy7aZ@cluster0.kh0fh.mongodb.net/innovators_marketplace?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: your_jwt_secret_key
      - key: CLOUDINARY_CLOUD_NAME
        value: dk6nfol6b
      - key: CLOUDINARY_API_KEY
        value: "512913691958756"
      - key: CLOUDINARY_API_SECRET
        value: OTV9_c49lbH6xDVKQZyFCGbkWmo
      - key: PORT
        value: "10000"
      - key: CI
        value: "false"
