services:
  - type: web
    name: windsurf-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://mdurgaprasad2422:1IJpgp0ODukxy7aZ@cluster0.kh0fh.mongodb.net/innovators_marketplace?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: your_jwt_secret_key
      - key: CLOUDINARY_CLOUD_NAME
        value: dk6nfol6b
      - key: CLOUDINARY_API_KEY
        value: "512913691958756"
      - key: CLOUDINARY_API_SECRET
        value: OTV9_c49lbH6xDVKQZyFCGbkWmo
      - key: STRIPE_SECRET_KEY
        sync: false

  - type: web
    name: windsurf-frontend
    env: node
    buildCommand: |
      cd client
      npm install
      npm run build
      mkdir -p /opt/render/project/src/client/build
      cp -r build/* /opt/render/project/src/client/build/
    startCommand: cd client && npx serve -s build
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://windsurf-backend.onrender.com
      - key: REACT_APP_SOCKET_URL
        value: https://windsurf-backend.onrender.com
