services:
  - type: web
    name: windsurf-app
    env: node
    buildCommand: |
      npm install
      cd client
      npm install
      npm run build
      cd ..
      ls -la
      ls -la client/build
    startCommand: |
      echo "Current directory contents:"
      ls -la
      echo "Client build directory contents:"
      ls -la client/build
      node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://mdurgaprasad2422:1IJpgp0ODukxy7aZ@cluster0.kh0fh.mongodb.net/innovators_marketplace?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: your_jwt_secret_key
      - key: CLOUDINARY_CLOUD_NAME
        value: dk6nfol6b
      - key: CLOUDINARY_API_KEY
        value: "512913691958756"
      - key: CLOUDINARY_API_SECRET
        value: OTV9_c49lbH6xDVKQZyFCGbkWmo
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: PORT
        value: "10000"
