services:
  - type: web
    name: windsurf-app
    env: node
    buildCommand: |
      # Install backend dependencies
      npm install
      
      # Build frontend
      cd client
      npm install
      CI=false npm run build
      
      # Debug info
      echo "===== DEBUGGING INFO ====="
      echo "Current location:"
      pwd
      echo "Build folder contents:"
      ls -la build
      
      # Create and copy to specific location
      mkdir -p /opt/render/project/src/client/build
      cp -r build/* /opt/render/project/src/client/build/
      
      # Verify copy
      echo "Destination folder contents:"
      ls -la /opt/render/project/src/client/build/
      
      # Return to root
      cd ..
    startCommand: |
      # Verify files before starting
      echo "===== STARTUP VERIFICATION ====="
      echo "Current directory:"
      pwd
      echo "Client build directory contents:"
      ls -la client/build
      
      # Start server
      node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://mdurgaprasad2422:1IJpgp0ODukxy7aZ@cluster0.kh0fh.mongodb.net/innovators_marketplace?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: your_jwt_secret_key
      - key: CLOUDINARY_CLOUD_NAME
        value: dk6nfol6b
      - key: CLOUDINARY_API_KEY
        value: "512913691958756"
      - key: CLOUDINARY_API_SECRET
        value: OTV9_c49lbH6xDVKQZyFCGbkWmo
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: PORT
        value: "10000"
      - key: CI
        value: "false"
